### ISSUE TITLE
Update scorpio version

### ISSUE THREAD

**Issue by brechtvdv** [FIWARE/tutorials.Linked-Data#17]
To fix the issue with the trailing slash (https://github.com/ScorpioBroker/ScorpioBroker/issues/52),
please update the SCORPIO_VERSION variable to 1.0.0

**Comment by brechtvdv** [comment]
Although, when updating scorpio to 1.0.0, the temporal representation endpoint does not return data while this was still working with 0.9.5

**Comment by jason-fox** [comment]
Fixed with 91a0aae
