### ISSUE TITLE
GET Query with   FQN renders []

### ISSUE THREAD

**Issue by 181502** [FIWARE/tutorials.Linked-Data#6]
Hi,

Prompted by a request from ETSI-CIM group to review the tutorial, I encountered the following. After I successfully added 2 buildings to Orion-LD, I tried tteh GET query from the README:

curl -G -X GET   'http://localhost:1026/ngsi-lv1/entities'   -d 'type=https://uri.fiware.org/ns/datamodels/Building'

This returned a empty list []

However, the query without the FQN does deliver results. Am I missing something?

TIA,
rob

**Comment by jason-fox** [comment]
This is due to a change in the FIWARE Data Models - the tutorial needs to be updated to fully align:

`https://uri.fiware.org/ns/datamodels/Building` has become `https://uri.fiware.org/ns/datamodels#Building` 

```console
curl -G -X GET \
  'http://localhost:1026/ngsi-ld/v1/entities' \
  -H 'Accept: application/ld+json' \
  -d 'type=https://uri.fiware.org/ns/datamodels#Building'
```



See also - https://github.com/FIWARE/tutorials.Linked-Data/pull/5/

**Comment by 181502** [comment]
Hi Jason,

that was also my suspicion. However, replacing / with a # also results in an empty set…
Any ideas?

regards,
rob

--__--_-_-_-__-_____----_-___--_---__-__-__--_-_-
rob van den berg   r.vandenberg@tisa.org
+31 624269585,  Eindhoven(NL) NLD-YH.RL

On 19 August 2019 at 16:56:31, Jason Fox (notifications@github.com) wrote:

This is due to a change in the FIWARE Data Models - the tutorial needs to be updated to fully align:

https://uri.fiware.org/ns/datamodels/Building has become https://uri.fiware.org/ns/datamodels#Building`

curl -G -X GET \
  'http://localhost:1026/ngsi-ld/v1/entities' \
  -H 'Accept: application/ld+json' \
  -d 'type=https://uri.fiware.org/ns/datamodels#Building'
See also - #5

**Comment by jason-fox** [comment]
The `#` needs to be URL encoded:

```console
curl -X GET \
  'http://localhost:1026/ngsi-ld/v1/entities?type=https://uri.fiware.org/ns/datamodels%23Building' \
  -H 'Accept: application/ld+json'
```

**Comment by 181502** [comment]
Thx,

I could have thought of that myself…

cheers,
rob

--__--_-_-_-__-_____----_-___--_---__-__-__--_-_-
rob van den berg   r.vandenberg@tisa.org
+31 624269585,  Eindhoven(NL) NLD-YH.RL

On 20 August 2019 at 08:11:28, Jason Fox (notifications@github.com) wrote:

curl -X GET \
  'http://localhost:1026/ngsi-ld/v1/entities?type=https://uri.fiware.org/ns/datamodels%23Building' \
  -H 'Accept: application/ld+json'
